services:
  mariadb:
    image: bitnami/mariadb:10.6-debian-12
    container_name: laravel-mariadb-02
    ports:
      - 39911:3306
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    networks:
      - network1
  laravel:
    image: "bitnami/laravel:10-debian-12"
    container_name: laravel-project02
    volumes:
      - /var/home/myapp/laravel/project02/application/:/app 
    ports:
      - 39912:8000
    env_file:
      - .env
    environment:
      LARAVEL_DATABASE_PORT_NUMBER: ${LARAVEL_DATABASE_PORT_NUMBER}
      LARAVEL_DATABASE_HOST: ${LARAVEL_DATABASE_HOST}
      LARAVEL_DATABASE_USER: ${LARAVEL_DATABASE_USER}
      LARAVEL_DATABASE_PASSWORD: ${LARAVEL_DATABASE_PASSWORD}
      LARAVEL_SKIP_COMPOSER_UPDATE: ${LARAVEL_SKIP_COMPOSER_UPDATE}
      LARAVEL_DATABASE_NAME: ${LARAVEL_DATABASE_NAME}
    networks:
      - network1
  redis:
    image: bitnami/redis:7.4-debian-12
    container_name: laravel-project02-redis
    ports:
      - 39915:6379
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    networks:
      - network1
networks:
  network1:
    name: network-43
    external: true
